# Generated by Django 5.2.1 on 2026-04-07 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deals', '0008_fill_our_entity_for_existing_deals'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('license_number', models.CharField(blank=True, max_length=50, verbose_name='Номер ВУ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водители',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название / марка')),
                ('reg_number', models.CharField(max_length=30, unique=True, verbose_name='Гос. номер')),
                ('capacity_tons', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Грузоподъёмность (т)')),
                ('volume_m3', models.DecimalField(decimal_places=2, default=0, help_text='Оставьте 0 если неизвестно', max_digits=6, verbose_name='Объём кузова (м³)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
            ],
            options={
                'verbose_name': 'Транспортное средство',
                'verbose_name_plural': 'Транспортные средства',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('delivery', 'Отгрузка (к клиенту)'), ('return', 'Возврат (от клиента)')], default='delivery', max_length=20, verbose_name='Направление')),
                ('planned_date', models.DateField(verbose_name='Плановая дата')),
                ('planned_time', models.TimeField(blank=True, null=True, verbose_name='Плановое время')),
                ('actual_date', models.DateField(blank=True, null=True, verbose_name='Фактическая дата')),
                ('address', models.TextField(blank=True, help_text='По умолчанию берётся адрес из сделки', verbose_name='Адрес')),
                ('status', models.CharField(choices=[('planned', 'Запланирован'), ('in_progress', 'В пути'), ('completed', 'Выполнен'), ('cancelled', 'Отменён')], default='planned', max_length=20, verbose_name='Статус')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость рейса (₽)')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='deals.deal', verbose_name='Сделка')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='delivery.driver', verbose_name='Водитель')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='delivery.vehicle', verbose_name='Транспортное средство')),
            ],
            options={
                'verbose_name': 'Рейс',
                'verbose_name_plural': 'Рейсы',
                'ordering': ['-planned_date', '-created_at'],
            },
        ),
    ]
