# Generated by Django 5.2.1 on 2026-04-07 07:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Номер счёта')),
                ('invoice_type', models.CharField(choices=[('rental', 'Аренда'), ('deposit', 'Залог'), ('penalty', 'Штраф/пеня'), ('repair', 'Ремонт'), ('non_return', 'Невозврат')], default='rental', max_length=20, verbose_name='Тип счёта')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Дата оплаты')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('sent', 'Отправлен'), ('paid', 'Оплачен'), ('overdue', 'Просрочен'), ('cancelled', 'Отменён')], default='draft', max_length=20, verbose_name='Статус')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма без НДС')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='НДС')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Итого')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Счёт',
                'verbose_name_plural': 'Счета',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('qty', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Кол-во')),
                ('unit', models.CharField(default='шт', max_length=20, verbose_name='Ед. изм.')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
            ],
            options={
                'verbose_name': 'Позиция счёта',
                'verbose_name_plural': 'Позиции счёта',
            },
        ),
        migrations.CreateModel(
            name='NonReturnAct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Номер акта')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма к взысканию')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Акт невозврата',
                'verbose_name_plural': 'Акты невозврата',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='NonReturnActItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_issued', models.IntegerField(verbose_name='Выдано, шт')),
                ('quantity_returned', models.IntegerField(default=0, verbose_name='Возвращено, шт')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за ед.')),
            ],
            options={
                'verbose_name': 'Позиция акта невозврата',
                'verbose_name_plural': 'Позиции акта невозврата',
            },
        ),
        migrations.CreateModel(
            name='ShippingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Номер')),
                ('date', models.DateField(verbose_name='Дата')),
                ('doc_type', models.CharField(choices=[('issue', 'Акт выдачи (отгрузка)'), ('return', 'Акт возврата'), ('partial_return', 'Акт частичного возврата')], max_length=20, verbose_name='Тип документа')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Документ отгрузки',
                'verbose_name_plural': 'Документы отгрузки',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ShippingDocumentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена за ед.')),
            ],
            options={
                'verbose_name': 'Позиция документа',
                'verbose_name_plural': 'Позиции документа',
            },
        ),
    ]
