# Generated by Django 5.2.1 on 2026-04-07 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('deals', '0001_initial'),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='deals.deal', verbose_name='Сделка'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.invoice', verbose_name='Счёт'),
        ),
        migrations.AddField(
            model_name='nonreturnact',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_return_acts', to='deals.deal', verbose_name='Сделка'),
        ),
        migrations.AddField(
            model_name='nonreturnactitem',
            name='act',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.nonreturnact'),
        ),
        migrations.AddField(
            model_name='nonreturnactitem',
            name='equipment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipment.equipmenttype', verbose_name='Тип оборудования'),
        ),
        migrations.AddField(
            model_name='shippingdocument',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_docs', to='deals.deal', verbose_name='Сделка'),
        ),
        migrations.AddField(
            model_name='shippingdocumentitem',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.shippingdocument', verbose_name='Документ'),
        ),
        migrations.AddField(
            model_name='shippingdocumentitem',
            name='equipment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipment.equipmenttype', verbose_name='Тип оборудования'),
        ),
    ]
