# Generated by Django 5.2.1 on 2026-04-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('algorithm_code', models.CharField(choices=[('area_based', 'По площади (строительные леса)'), ('tower', 'Вышки-туры'), ('daily_rate', 'Посуточная (любая техника)')], default='daily_rate', max_length=50, verbose_name='Алгоритм расчёта')),
                ('deposit_pct_default', models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='Залог % (по умолч.)')),
                ('use_city_coeff', models.BooleanField(default=True, verbose_name='Применять городской коэф.')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('ordering', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категория техники',
                'verbose_name_plural': 'Категории техники',
                'ordering': ['ordering', 'name'],
            },
        ),
    ]
