# Generated by Django 5.2.1 on 2026-04-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingCoefficientSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_coefficients', models.JSONField(blank=True, default=dict, verbose_name='Коэффициенты городов')),
                ('scaffold_season_coeff_default', models.DecimalField(decimal_places=3, default=1.2, max_digits=6, verbose_name='Сезонный коэф. (леса) по умолчанию')),
                ('scaffold_price_coeff_default', models.DecimalField(decimal_places=3, default=1.15, max_digits=6, verbose_name='Коэф. цен (леса) по умолчанию')),
                ('tower_psrv21_model_coeff', models.DecimalField(decimal_places=3, default=0.85, max_digits=6, verbose_name='Коэф. модели ПСРВ-21')),
                ('tower_psrv22_model_coeff', models.DecimalField(decimal_places=3, default=1.05, max_digits=6, verbose_name='Коэф. модели ПСРВ-22')),
                ('tower_psrv22_extra_charge', models.DecimalField(decimal_places=2, default=50.0, max_digits=8, verbose_name='Доп. наценка ПСРВ-22 (руб.)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройки коэффициентов',
                'verbose_name_plural': 'Настройки коэффициентов',
            },
        ),
    ]
