# Generated by Django 5.2.1 on 2026-04-07 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField(default=0, verbose_name='Порядок')),
                ('pricing_params', models.JSONField(default=dict, verbose_name='Параметры расчёта')),
                ('total_area', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Площадь (м²)')),
                ('daily_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Суточная стоимость')),
                ('total_rental', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Итого аренда')),
                ('market_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Рыночная стоимость')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма залога')),
            ],
            options={
                'verbose_name': 'Раздел сделки',
                'verbose_name_plural': 'Разделы сделки',
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='DealStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=30, verbose_name='Старый статус')),
                ('new_status', models.CharField(max_length=30, verbose_name='Новый статус')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'История статусов',
                'verbose_name_plural': 'История статусов',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='PartialReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateField(verbose_name='Дата возврата')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма к оплате за период')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Частичный возврат',
                'verbose_name_plural': 'Частичные возвраты',
                'ordering': ['-return_date'],
            },
        ),
        migrations.CreateModel(
            name='PartialReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_returned', models.IntegerField(verbose_name='Возвращено, шт')),
            ],
            options={
                'verbose_name': 'Позиция возврата',
                'verbose_name_plural': 'Позиции возврата',
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Номер сделки')),
                ('status', models.CharField(choices=[('new', 'Новая заявка'), ('calculation', 'Расчёт'), ('confirmed', 'Подтверждена'), ('contract_signed', 'Договор подписан'), ('invoice_sent', 'Счёт выставлен'), ('paid', 'Оплачено'), ('delivery', 'Отгрузка'), ('rented', 'В аренде'), ('partial_return', 'Частичный возврат'), ('returned', 'Возвращено'), ('overdue', 'Просрочено'), ('cancelled', 'Отменена'), ('non_return', 'Акт невозврата')], default='new', max_length=30, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала аренды')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания аренды')),
                ('actual_return_date', models.DateField(blank=True, null=True, verbose_name='Фактический возврат')),
                ('city', models.CharField(choices=[('Екатеринбург', 'Екатеринбург'), ('Пермь', 'Пермь'), ('Новосибирск', 'Новосибирск'), ('Челябинск', 'Челябинск')], default='Екатеринбург', max_length=50, verbose_name='Город')),
                ('delivery_address', models.TextField(blank=True, verbose_name='Адрес доставки')),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость доставки (1 рейс)')),
                ('vat_mode', models.CharField(choices=[('no_vat', 'Без НДС'), ('with_vat', 'С НДС (20%)')], default='no_vat', max_length=20, verbose_name='НДС')),
                ('deposit_pct', models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='Залог %')),
                ('total_area', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Площадь (м²)')),
                ('rental_days', models.IntegerField(default=30, verbose_name='Срок аренды (дней)')),
                ('daily_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Суточная стоимость')),
                ('total_rental', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Итого аренда')),
                ('market_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Рыночная стоимость оборудования')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма залога')),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Итого к оплате')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('contract_number', models.CharField(blank=True, max_length=100, verbose_name='Номер договора')),
                ('contract_date', models.DateField(blank=True, null=True, verbose_name='Дата договора')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='clients.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Сделка',
                'verbose_name_plural': 'Сделки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealEquipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Рыночная цена ед.')),
                ('daily_rental_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Суточная ставка (руб./ед.)')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_items', to='deals.deal', verbose_name='Сделка')),
            ],
            options={
                'verbose_name': 'Позиция оборудования',
                'verbose_name_plural': 'Позиции оборудования',
            },
        ),
    ]
