# Generated by Django 5.2.1 on 2026-04-07 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deals', '0001_initial'),
        ('equipment', '0001_initial'),
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealequipmentitem',
            name='equipment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipment.equipmenttype', verbose_name='Тип оборудования'),
        ),
        migrations.AddField(
            model_name='dealsection',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pricing.equipmentcategory', verbose_name='Категория техники'),
        ),
        migrations.AddField(
            model_name='dealsection',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='deals.deal', verbose_name='Сделка'),
        ),
        migrations.AddField(
            model_name='dealequipmentitem',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_items', to='deals.dealsection', verbose_name='Раздел'),
        ),
        migrations.AddField(
            model_name='dealstatushistory',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='deals.deal'),
        ),
        migrations.AddField(
            model_name='partialreturn',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partial_returns', to='deals.deal', verbose_name='Сделка'),
        ),
        migrations.AddField(
            model_name='partialreturnitem',
            name='equipment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipment.equipmenttype', verbose_name='Тип оборудования'),
        ),
        migrations.AddField(
            model_name='partialreturnitem',
            name='partial_return',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='deals.partialreturn'),
        ),
    ]
