# Generated by Django 5.2.1 on 2026-04-07 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deals', '0001_initial'),
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('unit', models.CharField(default='шт', max_length=20, verbose_name='Ед. изм.')),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Рыночная стоимость ед.')),
                ('price_coefficient', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Коэффициент цены')),
                ('daily_rental_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Суточная ставка аренды (руб.)')),
                ('weight_per_unit', models.DecimalField(decimal_places=3, default=0, max_digits=8, verbose_name='Вес ед. (кг)')),
                ('volume_per_unit', models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='Объём ед. (м3)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_types', to='pricing.equipmentcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Тип оборудования',
                'verbose_name_plural': 'Типы оборудования',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Поступление'), ('out_reserve', 'Резервирование'), ('out_rent', 'Выдача в аренду'), ('return', 'Возврат с аренды'), ('cancel_reserve', 'Снятие резерва'), ('repair_out', 'Отправка на ремонт'), ('repair_in', 'Возврат с ремонта'), ('writeoff', 'Списание'), ('adjustment', 'Корректировка')], max_length=20, verbose_name='Тип движения')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_by', models.CharField(blank=True, max_length=100, verbose_name='Создал')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='deals.deal', verbose_name='Сделка')),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='equipment.equipmenttype', verbose_name='Тип оборудования')),
            ],
            options={
                'verbose_name': 'Движение оборудования',
                'verbose_name_plural': 'Движения оборудования',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_total', models.IntegerField(default=0, verbose_name='Всего')),
                ('quantity_reserved', models.IntegerField(default=0, verbose_name='Зарезервировано')),
                ('quantity_rented', models.IntegerField(default=0, verbose_name='В аренде')),
                ('quantity_repair', models.IntegerField(default=0, verbose_name='На ремонте')),
                ('min_stock_level', models.IntegerField(default=0, verbose_name='Мин. запас')),
                ('equipment_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='equipment.equipmenttype', verbose_name='Тип оборудования')),
            ],
            options={
                'verbose_name': 'Остаток на складе',
                'verbose_name_plural': 'Остатки на складе',
            },
        ),
    ]
