# Generated by Django 5.2.1 on 2026-04-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_type', models.CharField(choices=[('individual', 'Физическое лицо'), ('company', 'Юридическое лицо')], default='individual', max_length=20, verbose_name='Тип клиента')),
                ('name', models.CharField(max_length=255, verbose_name='Имя / Наименование')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('city', models.CharField(default='Екатеринбург', max_length=100, verbose_name='Город')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('passport_series', models.CharField(blank=True, max_length=10, verbose_name='Серия паспорта')),
                ('passport_number', models.CharField(blank=True, max_length=20, verbose_name='Номер паспорта')),
                ('passport_issued_by', models.CharField(blank=True, max_length=255, verbose_name='Кем выдан')),
                ('passport_issued_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('registration_address', models.TextField(blank=True, verbose_name='Адрес регистрации')),
                ('company_full_name', models.CharField(blank=True, max_length=500, verbose_name='Полное наименование')),
                ('inn', models.CharField(blank=True, max_length=20, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=20, verbose_name='КПП')),
                ('ogrn', models.CharField(blank=True, max_length=20, verbose_name='ОГРН')),
                ('director', models.CharField(blank=True, max_length=255, verbose_name='Руководитель (ФИО)')),
                ('director_short', models.CharField(blank=True, max_length=100, verbose_name='Руководитель (И.О. Фамилия)')),
                ('director_title', models.CharField(blank=True, default='Директор', max_length=100, verbose_name='Должность руководителя')),
                ('legal_address', models.TextField(blank=True, verbose_name='Юридический адрес')),
                ('bank_name', models.CharField(blank=True, max_length=255, verbose_name='Банк')),
                ('bank_account', models.CharField(blank=True, max_length=30, verbose_name='Расчётный счёт')),
                ('bank_bik', models.CharField(blank=True, max_length=20, verbose_name='БИК')),
                ('bank_corr_account', models.CharField(blank=True, max_length=30, verbose_name='Корр. счёт')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['-created_at'],
            },
        ),
    ]
