# Generated by Django 5.2.1 on 2026-04-07 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('deals', '0006_repair_dealequipmentitem_section_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название шаблона')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='Код')),
                ('body', models.TextField(help_text='Синтаксис Django Template: {{ our.name }}, {{ client.inn }}, {{ deal.number }}, {{ contract.number }}, {{ contract.date|date:"d.m.Y" }} и т.д.', verbose_name='Текст шаблона')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Шаблон договора',
                'verbose_name_plural': 'Шаблоны договоров',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OurLegalEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('individual', 'Физическое лицо / ИП'), ('company', 'Юридическое лицо')], default='company', max_length=20, verbose_name='Тип')),
                ('name', models.CharField(max_length=255, verbose_name='Краткое наименование / ФИО')),
                ('is_default', models.BooleanField(default=False, verbose_name='Использовать по умолчанию')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Почтовый адрес')),
                ('city', models.CharField(blank=True, default='Екатеринбург', max_length=100, verbose_name='Город')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('passport_series', models.CharField(blank=True, max_length=10, verbose_name='Серия паспорта')),
                ('passport_number', models.CharField(blank=True, max_length=20, verbose_name='Номер паспорта')),
                ('passport_issued_by', models.CharField(blank=True, max_length=255, verbose_name='Кем выдан')),
                ('passport_issued_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи паспорта')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('registration_address', models.TextField(blank=True, verbose_name='Адрес регистрации')),
                ('company_full_name', models.CharField(blank=True, max_length=500, verbose_name='Полное наименование')),
                ('inn', models.CharField(blank=True, max_length=20, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=20, verbose_name='КПП')),
                ('ogrn', models.CharField(blank=True, max_length=20, verbose_name='ОГРН / ОГРНИП')),
                ('director', models.CharField(blank=True, max_length=255, verbose_name='Подписант (ФИО полностью)')),
                ('director_short', models.CharField(blank=True, max_length=100, verbose_name='Подписант (И.О. Фамилия)')),
                ('director_title', models.CharField(blank=True, default='Директор', max_length=100, verbose_name='Должность подписанта')),
                ('legal_address', models.TextField(blank=True, verbose_name='Юридический адрес')),
                ('bank_name', models.CharField(blank=True, max_length=255, verbose_name='Банк')),
                ('bank_account', models.CharField(blank=True, max_length=30, verbose_name='Расчётный счёт')),
                ('bank_bik', models.CharField(blank=True, max_length=20, verbose_name='БИК')),
                ('bank_corr_account', models.CharField(blank=True, max_length=30, verbose_name='Корр. счёт')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Наше юр. лицо / ИП',
                'verbose_name_plural': 'Наши юр. лица и ИП',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, verbose_name='Номер договора')),
                ('contract_date', models.DateField(verbose_name='Дата договора')),
                ('rendered_html', models.TextField(verbose_name='Сгенерированный текст (HTML)')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_contracts', to='clients.client', verbose_name='Клиент')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_contracts', to='deals.deal', verbose_name='Сделка')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_contracts', to='documents.contracttemplate', verbose_name='Шаблон')),
                ('our_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_contracts', to='documents.ourlegalentity', verbose_name='Наше юр. лицо')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
                'ordering': ['-contract_date', '-created_at'],
            },
        ),
    ]
